addons:
  sonarcloud:
    organization: mariuszfoltak
    token:
      secure: w4uk8XJkFLC8Og52ZjZ2aItGIeeljFm65jL1fp1XeDiHMPb9+i/11l2UhYh/Uv8fbh7iiFreeY7dmuUSEYbzVlzJHR38H6x0PzRZk6hgE6/eUhNgA6zhydyZcc/o6V1W3CuEsG82lRAU0cKFgLcNT22JE5nxDoipaF6W0eJcPab/y6y6PaPBBszflqUC0iWq/aD2xYJWYP9QFBIinPOqoxmhkY1abf/BedGaOenQUwY7D62mwSXCixlXTrPNjQyonAVd5VITYAtMFDpEq2TCHHIDsyVC6Pf3GAmF2PHDkAdMZnL4y/Tp1YB/Z2avfGZKROfbvDyXNbHinGlpZdP5pUJFfVILwgdemjaJs/afAZ2SGhZZ5Ezlfa6Rf5zW2v6Z3tZvFoaYRDwSuJerdDehrKE2E6anQkR6GGfJqhkdt8gdkalXbL5kI3nLYaqoJP/NmPA1U8kOxGBxYmHkAPKH60wZrKDMoW/KisP8UfJVLyGqvU+34dbptpHw9l5o1KPLndQczJ/xMwXM52Y+vXFuEzJk3QzEpRA6bt0W7K9JLgFsC3VrU2cYC+y4+A5gsNwzp3TmEb0SiLACTVGcim4M8WF/s66Exd2GG92OZZyO1z/armeV4l9nE1oTcyBwNcxf4jG761E/l2q28d9khan0Xzg/qG9aXTCqeRkVO9UoMnY=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
language: java
script:
- mvn clean install jacoco:report sonar:sonar -Dsonar.projectKey=mariuszfoltak_polish-identification-numbers
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_38e47955425c_key -iv $encrypted_38e47955425c_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
- gpg --fast-import .travis/gpg.asc
- cp .travis/maven.settings.xml $HOME/.m2/settings.xml
env:
  global:
  - secure: NQ0AChTOAS0MbxpohqI+05IV3n5yCgUp9MVAT8MaZ59Tqr0qWUp7k5TadLfRx7C8fUiiicLec58D7bARLES9LUiQ1RcZbWizLCVGcX/cSCesWvj+tY3OGsQwKArLFc0xjary+c+Vg8Fh+9Z5+CoRX1r6+aUadanIk5mk4vAKvG9HQt2DKPVAoiNmwjvSxMdZGzQFCMEdBVUqukG5uqLmSHVQHX4xJ5h3eIvg28f0pKkH+SXfNRa7BK3Chzwki3ZqPo44oY165mMoIZTAlIKPvE0b4qr42xpNmSjhx1bj7q+Q4rxxFDZt1lcqXD7ULKLRd/4zLd/irQovNtI1o7b3t86av3IJXromVDfs39St3+X9XNCP2fWuIiyxj56mpotAC+RmtwTiSm3atps14DwAdRWfveTRbVjdWW2K5RUPFHNtB0hMzHfG8FV7I2jg/rY9Tg4b4D/wG74gKrBy6VG6w65cm4S8OHEYkoqSpXzaQjrdRZmg9U+f/5+24f6sQT3VPT9NByfy0edp5KOP3OOF8bDR0YJMFm/ii3Y+tWn2DrL5MiB1jqf+rR53axoWbNfZMeuIlevWJOXYJAa5UcX01qSVGRA/M18LCuk/7tRJqynfY9HeGl19oer4J4mKVRX+Gj7IHF6q4myRk9J0YffjENX3HIxl3aBfjLVk38tayb0=
  - secure: iwxiQVLoBF0e1My/Q+QzFK5I3iJ2EXaAIv4JPa+45cljxQqHeJL7O6eqkkyOsMyD4CFKt2YKgYVK26EbWtblHf5gcU/LxVsIwoRx4oYpJ0If6PxeQ9KwQsc95k2ajPgrxrsQdEl14rqaiQUyvXbNbtDHgd6wRgmcYixGm5nxwWdIusENRcobdsnwI6aQ3BTiSiJ/seUhJWq2+dH4b58izOZz/bJVM/5/CA4extgW0ix8rb374tCrPdg6mD2LCmv4gKb+AUBbBSaeHEZSfruX/rpmkZuaZ8TKvhAUDkwdJbbslleHPDQ6w8ajX0U4AOQ3snFSWdK3VzAd1mvXwhQkkbe+lzBlaLXPhf0PGbh8t07oAszHgSeWd456jGOsp6XV1sN+uo4ETB7ZJ89QDkqsj61a5r4/WDuvfquaSAwPU5c3PIv+pxHXZXvYhGACp81OrttE97Wx9Gi5jCP5R/P2KpcNaoAMDZQXnuNtRfe+OpLV5Yl44pPpG+j+6BmaqVdB0R2S6TMjblmTQ4T99t5GDNDfY1ywlmtHYEhstY2vs5gKeWThP4fSAla0dKu7BJNo/CqIBXf5fCWCzVZLdeDYDkinS2rSieH9H0RyI79JGiYR3Ir4l1Su1DNGsYiFYx1J+SDe1EzQdYUNi6t8uRAK4RooadRBfuG5tP+YvPFsmLM=
