addons:
  sonarcloud:
    organization: mariuszfoltak
    token:
      secure: w4uk8XJkFLC8Og52ZjZ2aItGIeeljFm65jL1fp1XeDiHMPb9+i/11l2UhYh/Uv8fbh7iiFreeY7dmuUSEYbzVlzJHR38H6x0PzRZk6hgE6/eUhNgA6zhydyZcc/o6V1W3CuEsG82lRAU0cKFgLcNT22JE5nxDoipaF6W0eJcPab/y6y6PaPBBszflqUC0iWq/aD2xYJWYP9QFBIinPOqoxmhkY1abf/BedGaOenQUwY7D62mwSXCixlXTrPNjQyonAVd5VITYAtMFDpEq2TCHHIDsyVC6Pf3GAmF2PHDkAdMZnL4y/Tp1YB/Z2avfGZKROfbvDyXNbHinGlpZdP5pUJFfVILwgdemjaJs/afAZ2SGhZZ5Ezlfa6Rf5zW2v6Z3tZvFoaYRDwSuJerdDehrKE2E6anQkR6GGfJqhkdt8gdkalXbL5kI3nLYaqoJP/NmPA1U8kOxGBxYmHkAPKH60wZrKDMoW/KisP8UfJVLyGqvU+34dbptpHw9l5o1KPLndQczJ/xMwXM52Y+vXFuEzJk3QzEpRA6bt0W7K9JLgFsC3VrU2cYC+y4+A5gsNwzp3TmEb0SiLACTVGcim4M8WF/s66Exd2GG92OZZyO1z/armeV4l9nE1oTcyBwNcxf4jG761E/l2q28d9khan0Xzg/qG9aXTCqeRkVO9UoMnY=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
language: java
script:
- mvn clean install jacoco:report sonar:sonar -Dsonar.projectKey=mariuszfoltak_polish-identification-numbers
  --settings "${TRAVIS_BUILD_DIR}/.travis/maven.settings.xml"
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
- gpg --fast-import .travis/gpg.asc
env:
  global:
  - secure: NQ0AChTOAS0MbxpohqI+05IV3n5yCgUp9MVAT8MaZ59Tqr0qWUp7k5TadLfRx7C8fUiiicLec58D7bARLES9LUiQ1RcZbWizLCVGcX/cSCesWvj+tY3OGsQwKArLFc0xjary+c+Vg8Fh+9Z5+CoRX1r6+aUadanIk5mk4vAKvG9HQt2DKPVAoiNmwjvSxMdZGzQFCMEdBVUqukG5uqLmSHVQHX4xJ5h3eIvg28f0pKkH+SXfNRa7BK3Chzwki3ZqPo44oY165mMoIZTAlIKPvE0b4qr42xpNmSjhx1bj7q+Q4rxxFDZt1lcqXD7ULKLRd/4zLd/irQovNtI1o7b3t86av3IJXromVDfs39St3+X9XNCP2fWuIiyxj56mpotAC+RmtwTiSm3atps14DwAdRWfveTRbVjdWW2K5RUPFHNtB0hMzHfG8FV7I2jg/rY9Tg4b4D/wG74gKrBy6VG6w65cm4S8OHEYkoqSpXzaQjrdRZmg9U+f/5+24f6sQT3VPT9NByfy0edp5KOP3OOF8bDR0YJMFm/ii3Y+tWn2DrL5MiB1jqf+rR53axoWbNfZMeuIlevWJOXYJAa5UcX01qSVGRA/M18LCuk/7tRJqynfY9HeGl19oer4J4mKVRX+Gj7IHF6q4myRk9J0YffjENX3HIxl3aBfjLVk38tayb0=
  - secure: IQL8VKlyRM3dhuHftchrzkeZuWcs+D4HN7T95Gb6y8dbDqwSI3FTF1V/s9jf1+PXwhtUz/D2EvtmWRJdujOQ1g6u4ju5jBQYGU68nH3zhh/jIMGSkmrnyE4bRChfC0ToojEQV0IbU9DqNXlOHlT1xYRdyl3HH2WD7QROdCe/K48ZzffKbHtqvwv5ZYBwNYUmonh+rBDYQIXj518gV8isLIWxzxHqWzUAOX4f6hQSbzjuwv2Rm3Ar3+GNF3dNBer+xR3gAb/q679bMbPDz5rQIdKpGKhFbtaBkTGfQS+Uofl9j4glBHNpye+wik4zZkRK8fyioK6FDjDQl4HBXUTVN77dLN5MjWVdsitxqb25Inn2o36pmk+Bl4T39eJjuUildvJLnJnrEQQ+6sX1EV5rCsYJvsx0Ut1as9MfNsHKVuU00isp2gPn1GWMj9eVkHpRVFl2j3IM6O54QpgOlSMi+40EdKdaLV2XJ5XiMnwMt6xtAlgaG5HgXjXxGOxrEWKBxuyr/gmK1YmmpEbjwvurREVcSJcfpdVmATlYydUVc+6Lzf68gybLyLCiVyzbHl+ZliDCTAOIEWOb9Gqr5yVBSNk+dOwI9Q29fscEQRAKkcZoArRrRXw68MTVojcvz9ZvaIYM2Wdh6Jc2P7qS9Bto7iWELWYl2Om9oNDk77o6a+A=
